name: Publish Release

# The workflow in the example below runs when the release event triggers with a Pull Request is closed and merged.
# For more information on the release event.
# See: [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release)

on:
  pull_request:
    types:
      - closed

jobs:
  # The the release job will only run if the pull request was also merged
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    # See: https://github.com/marketplace/actions/create-release
    - uses: ncipollo/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: <tofill>
        tag: <tofill>
        generateReleaseNotes: true
        draft: true
        prerelease: false
        makeLatest: true
        allowUpdates: true
        skipIfReleaseExists: true
        updateOnlyUnreleased: true
